site_name: lernOS für Dich Leitfaden
site_url: https://simondueckert.github.io/
docs_dir: src
site_dir: ../docs/en

nav:
    - Welcome: index.md
    - Introduction:
        - Knowledge Work and Lifelong Learning: 1-1-Lifelong-Learning-and-Knowledge-Work.md
        - lernOS Canvas: 1-2-lernOS-Canvas.md
        - lernOS Flow: 1-3-lernOS-Flow.md
        - lernOS Workplace: 1-4-lernOS-Workplace.md
        - lernOS Memex: 1-5-lernOS-Memex.md
    - Learning Paths:
        - Overview: 2-0-Learning-Paths.md
        - Learning Path Productive & Stressfree:
            - Top 10 Quellen zu GTD (Kata): 2-1-1-Kata-1.md
            - Zeug sammeln und Mind sweepen (Kata): 2-1-2-Kata-2.md
            - Richte deine GTD-Umgebung ein (Kata): 2-1-3-Kata-3.md
            - Welche Inbox(en) willst du verwenden? (Kata): 2-1-4-Kata-4.md
            - Welche Listen willst du anlegen und führen? (Kata): 2-1-5-Kata-5.md
            - Inbox Zero in 4 Schritten (Kata): 2-1-6-Kata-6.md
            - Richte deine Projektumgebung ein (Kata): 2-1-7-Kata-7.md
            - Lege deine Referenzablage an (Kata): 2-1-8-Kata-8.md
            - Mache ein Weekly Review (Kata): 2-1-9-Kata-9.md
            - Mache ein Daily Review (Kata): 2-1-10-Kata-10.md
            - Die 6 Fokushorizonte von Getting Things Done (Kata): 2-1-11-Kata-11.md
    - Appendix: 3-Appendix.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: en
    features:
      - navigation.sections
    icon:
      logo: material/home
      repo: fontawesome/brands/github

repo_name: 'simondueckert/lernos-4u-sap-lce'
repo_url: 'https://github.com/simondueckert/lernos-4u-sap-lce'

extra:
    homepage: https://lernos.org
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/lern_os
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/showcase/lern-os
        - icon: fontawesome/brands/github
          link: https://github.com/cogneon